import type { Metadata } from 'next';
import './globals.css';
import { StoryblokProvider } from './components/StoryblokProvider';

export const metadata: Metadata = {
  title: 'Asioso Storyblok',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang='en'>
        <body className={`antialiased`}>{children}</body>
      </html>
    </StoryblokProvider>
  );
}
